### PR TITLE
add server port

### PR DESCRIPTION
**Pull request by calistus-igwilo**
Add Server port from where the vite app can be accessed

### CODE REVIEW

**Comment by peculiaruc** [comment]
Hi what error are you facing here

**Comment by peculiaruc** [comment]
@calistus-igwilo Are that Codacy errors on pre-generated codes?

**Comment by calistus-igwilo** [comment]
@peculiaruc it was a lint error and it has been fixed. I will wait for @tamsay to merge his PR before I do a new PR. Thank you

**Comment by peculiaruc** [comment]
Great

**Pull request closed without merging**
