### PR TITLE
Feature/forget password

### PR DESCRIPTION
**Pull request by OluwasegunA**

### CODE REVIEW

**Comment by OluwasegunA** [comment]
This PR completes issues 73 & 74

**Comment by Honeyloveet** [comment]
@OluwasegunA fix the branch conflicts and codacy checks

**Comment by OluwasegunA** [comment]
@Honeyloveet Done

**Comment by Honeyloveet** [comment]
@OluwasegunA Codacy checks have failed please fix it.

**Comment by OluwasegunA** [comment]
@Honeyloveet Fixed now

**Pull request merged**
